export const PaymentModuleResourceKeys = {
    ytdEarning: {
        reportName: 'payment.ytdEarning.reportName',
        client: 'payment.ytdEarning.client',
        details: 'payment.ytdEarning.details',
        endingDate: 'payment.ytdEarning.endingDate',
        grossAmount: 'payment.ytdEarning.grossAmount',
        internalCompany: 'payment.ytdEarning.internalCompany',
        paymentReleaseDate: 'payment.ytdEarning.paymentReleaseDate',
        paymentTransNo: 'payment.ytdEarning.paymentTransNo',
        startingDate: 'payment.ytdEarning.startingDate',
        summary: 'payment.ytdEarning.summary',
        totalAmount: 'payment.ytdEarning.totalAmount',
        totalGrossAmount: 'payment.ytdEarning.totalGrossAmount',
        totalVacationAccured: 'payment.ytdEarning.totalVacationAccured',
        vacationaccured: 'payment.ytdEarning.vacationaccured',
        year: 'payment.ytdEarning.year',
        ei: 'payment.ytdEarning.ei',
        cpp: 'payment.ytdEarning.cpp',
        qpp: 'payment.ytdEarning.qpp',
        gsthst: 'payment.ytdEarning.gsthst',
        qst: 'payment.ytdEarning.qst',
        pst: 'payment.ytdEarning.pst',
        paymentTransFrom: 'payment.ytdEarning.paymentTransFrom',
        paymentTransTo: 'payment.ytdEarning.paymentTransTo',
        rateType: 'payment.ytdEarning.rateType',
        units: 'payment.ytdEarning.units',
        rate: 'payment.ytdEarning.rate',
        getReport: 'payment.ytdEarning.getReport',
        export: 'payment.ytdEarning.export',
        yearMaximumSourceDeduction: 'payment.ytdEarning.yearMaximumSourceDeduction',
        federalTax: 'payment.ytdEarning.federalTax',
        provincialTax: 'payment.ytdEarning.provincialTax',
        garnishments: 'payment.ytdEarning.garnishments',
        nonResidentWithHoldingTax: 'payment.ytdEarning.nonResidentWithHoldingTax',
        additionalTax: 'payment.ytdEarning.additionalTax',
        benefits: 'payment.ytdEarning.benefits',
        advances: 'payment.ytdEarning.advances',
        worker: 'payment.ytdEarning.worker',
        pip: 'payment.ytdEarning.pip',
        openingBalance: 'payment.ytdEarning.openingBalance',

        // lower case formats (for dynamic key finding; see payment-ytd-earnings-summary.component.ts:processData())
        federaltax: 'payment.ytdEarning.federalTax',
        provincialtax: 'payment.ytdEarning.provincialTax',
        nonresidentwithholdingtax: 'payment.ytdEarning.nonResidentWithHoldingTax',
        additionaltax: 'payment.ytdEarning.additionalTax',
    }
};
