// merge fix
// declare function require(name: string);
// const anyWindow = <any>window;

// import { environment } from '../environments/environment';


// anyWindow.api2Url = environment.apiUrl;
// anyWindow.rollbarConfig = environment.rollbar;

// anyWindow.$ = require('jquery');
// anyWindow.jQuery = $;
// anyWindow.moment = require('moment');
// anyWindow.toastr = require('toastr');
// anyWindow.Sortable = require('../../node_modules/sortablejs/Sortable.js');
// anyWindow.oreq = require('../../node_modules/oreq/src/oreq.js');

// require('jquery-ui');
// // require('webpack-jquery-ui');
// require('../../node_modules/jquery/dist/jquery.js');
// require('../../node_modules/angular/angular.js');
// require('../../node_modules/bootstrap/dist/js/bootstrap.js');
// require('../../node_modules/moment-range/dist/moment-range.js');
// require('../../node_modules/datejs/src/core/i18n.js');
// require('../../node_modules/datejs/src/core/core.js');
// require('../../node_modules/datejs/src/core/core-prototypes.js');
// require('../../node_modules/datejs/src/core/sugarpak.js');
// require('../../node_modules/datejs/src/core/format_parser.js');
// require('../../node_modules/datejs/src/core/parsing_operators.js');
// require('../../node_modules/datejs/src/core/parsing_translator.js');
// require('../../node_modules/datejs/src/core/parsing_grammar.js');
// require('../../node_modules/datejs/src/core/parser.js');
// require('../../node_modules/datejs/src/core/extras.js');
// require('../../node_modules/datejs/src/core/time_period.js');
// require('../../node_modules/datejs/src/core/time_span.js');
// require('../../node_modules/underscore/underscore.js');
// require('../../node_modules/lodash/lodash.js');
// require('@uirouter/angularjs');
// require('../../node_modules/angular-animate/angular-animate.js');
// require('../../node_modules/angular-filter/dist/angular-filter.js');
// require('../../node_modules/valdr/valdr.js');
// require('../../node_modules/valdr/valdr-message.js');
// require('../../node_modules/typeahead.js/dist/typeahead.bundle.js');
// require('../../node_modules/angular-sanitize/angular-sanitize.js');
// require('../../node_modules/angular-ui-bootstrap/dist/ui-bootstrap-tpls.js');
// require('../../node_modules/angular-translate/dist/angular-translate.js');
// require('../../node_modules/ui-select/dist/select.js');
// require('../../node_modules/angular-cookies/angular-cookies.js');
// require('../../node_modules/angular-resource/angular-resource.js');
// require('../../node_modules/angular-route/angular-route.js');
// require('../../node_modules/jquery-migrate/dist/jquery-migrate.js');
// require('../../node_modules/jquery-validation/dist/jquery.validate.js');
// require('../../node_modules/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js');
// require('../../node_modules/jquery-ajax-unobtrusive/dist/jquery.unobtrusive-ajax.js');
// require('../../node_modules/jquery.inputmask/dist/jquery.inputmask.bundle.js');
// require('../../node_modules/Select2/select2.js');
// require('../../vendor/jquery.signalR.js');
// require('../../node_modules/ngprogress/build/ngprogress.js');
// // require('../../node_modules/spin.js/spin.js');
// require('../../node_modules/angular-vs-repeat/src/angular-vs-repeat.js');
// require('../../node_modules/restangular/dist/restangular.js');
// require('../../node_modules/angular-busy/dist/angular-busy.js');
// require('../../node_modules/angular-dialog-service/dist/dialogs.js');
// require('../../node_modules/angular-dialog-service/dist/dialogs-default-translations.js');
// require('../../node_modules/angular-dashboard-framework/dist/angular-dashboard-framework-tpls.js');
// require('../../node_modules/angular-ui/build/angular-ui.js');
// require('../../node_modules/angular-ui/build/angular-ui-ieshiv.js');
// require('../../../../custom-vendor/prototype/prototype.js');
// require('../../../../custom-vendor/smart-table/smart-table.module.js');
// require('../../../../custom-vendor/smart-table/stAdvancedPipe.js');
// require('../../../../custom-vendor/smart-table/stAdvancedSearch.js');
// require('../../../../custom-vendor/smart-table/stColumnWidths.js');
// require('../../../../custom-vendor/smart-table/stCombineHorizontalScrolls.js');
// require('../../../../custom-vendor/smart-table/stDraggable.js');
// require('../../../../custom-vendor/smart-table/stFixedHeader.js');
// require('../../../../custom-vendor/smart-table/stHead.js');
// require('../../../../custom-vendor/smart-table/stInitilization.js');
// require('../../../../custom-vendor/smart-table/stOpenColumnView.js');
// require('../../../../custom-vendor/smart-table/stPagination.js');
// require('../../../../custom-vendor/smart-table/stPaginationScroll.js');
// require('../../../../custom-vendor/smart-table/stPaginationScrollSeparated.js');
// require('../../../../custom-vendor/smart-table/stPenName.js');
// require('../../../../custom-vendor/smart-table/stPipe.js');
// require('../../../../custom-vendor/smart-table/stRFixedHeader.js');
// require('../../../../custom-vendor/smart-table/stSearch.js');
// require('../../../../custom-vendor/smart-table/stSelectRow.js');
// require('../../../../custom-vendor/smart-table/stSelectRowInArray.js');
// require('../../../../custom-vendor/smart-table/stSort.js');
// require('../../../../custom-vendor/smart-table/stTable.js');
// require('../../../../custom-vendor/smart-table/stTableStruct.js');
// require('../../../../custom-vendor/abn-tree/abn_tree_directive.js');
// require('../../../../Content/extensions/oreq/oreq.smartTableAdapter.js');
// require('../../../../Content/extensions/filesaver/FileSaver.js');
// require('script-loader!blueimp-file-upload/js/vendor/jquery.ui.widget.js');
// require('script-loader!blueimp-load-image/js/load-image.all.min.js');
// require('script-loader!blueimp-canvas-to-blob/js/canvas-to-blob.js');
// require('script-loader!blueimp-file-upload/js/jquery.iframe-transport.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-process.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-image.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-audio.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-video.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-validate.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-ui.js');
// require('script-loader!blueimp-file-upload/js/jquery.fileupload-angular.js');
// require('script-loader!blueimp-tmpl/js/tmpl.js');
// require('../../node_modules/jquery-print-preview-plugin/src/jquery.print-preview.js');
// require('../../node_modules/angulartics/dist/angulartics.min.js');
// require('../../node_modules/angulartics-google-analytics/dist/angulartics-ga.min.js');
// require('../../node_modules/ng-rollbar/ng-rollbar.min.js');
// require('../../node_modules/ng-selectize/selectize/selectize.standalone.js');

// require('../../../../debug/Phoenix/app/app');
// require('../../../../debug/importer');
// require('./downgraded.directive.ts');
// require('./downgraded.service.ts');

// // require('./phoenix.loader-files');

// export const Phoenix = 'Phoenix';
