
// value format: '<Folder Name under Procom.Phoenix.CQL/Resources>.<fileName>.<Resource string defined in *.resx>'
export const ExpenseModuleResourceKeys = {
    search: {
        approversColumnHeader: 'expense.search.approversColumnHeader',
        clientNameColumnHeader: 'expense.search.clientNameColumnHeader',
        currencyColumnHeader: 'expense.search.currencyColumnHeader',
        expenseClaimSearchTitle: 'expense.search.expenseClaimSearchTitle',
        idColumnHeader: 'expense.search.idColumnHeader',
        noActiveWorkOrderMessage: 'expense.search.noActiveWorkOrderMessage',
        statusColumnHeader: 'expense.search.statusColumnHeader',
        submissionDateColumnHeader: 'expense.search.submissionDateColumnHeader',
        titleColumnHeader: 'expense.search.titleColumnHeader',
        totalColumnHeader: 'expense.search.totalColumnHeader',
        totalSummaryFormat: 'expense.search.totalSummaryFormat',
        workerNameColumnHeader: 'expense.search.workerNameColumnHeader',
        workOrderColumnHeader: 'expense.search.workOrderColumnHeader',
        newButton: 'expense.search.newButton',
        commentsColumnHeader: 'expense.search.commentsColumnHeader',
        fromDateColumnHeader: 'expense.search.fromDateColumnHeader',
        organizationInternalDisplayNameColumnHeader: 'expense.search.organizationInternalDisplayNameColumnHeader',
        toDateColumnHeader: 'expense.search.toDateColumnHeader',
        workOrderEndDateColumnHeader: 'expense.search.workOrderEndDateColumnHeader',
        workOrderStartDateColumnHeader: 'expense.search.workOrderStartDateColumnHeader',
        internalOrganizationDefinition1ColumnHeader: 'expense.search.internalOrganizationDefinition1ColumnHeader',
        openWorkorderInNewTab: 'expense.search.openWorkorderInNewTab',
        openExpenseInNewTab: 'expense.search.openExpenseInNewTab',
        openWorkerInNewTab: 'expense.search.openWorkerInNewTab',
    },
    create: {
        clientColumnHeader: 'expense.create.clientColumnHeader',
        descriptionColumnHeader: 'expense.create.descriptionColumnHeader',
        endDateColumnHeader: 'expense.create.endDateColumnHeader',
        startDateColumnHeader: 'expense.create.startDateColumnHeader',
        workerColumnHeader: 'expense.create.workerColumnHeader',
        workOrderColumnHeader: 'expense.create.workOrderColumnHeader',
    },
    itemList: {
        addBtn: 'expense.itemList.addBtn',
        loadingText: 'expense.itemList.loadingText',
        itemsTitle: 'expense.itemList.itemsTitle',
        categoryColumnHeader: 'expense.itemList.categoryColumnHeader',
        dateColumnHeader: 'expense.itemList.dateColumnHeader',
        merchantColumnHeader: 'expense.itemList.merchantColumnHeader',
        noteColumnHeader: 'expense.itemList.noteColumnHeader',
        totalColumnHeader: 'expense.itemList.totalColumnHeader',
        actionColumnHeader: 'expense.itemList.actionColumnHeader',
        totalSummaryFormat: 'expense.itemList.totalSummaryFormat',
        deleteItemMessage: 'expense.itemList.deleteItemMessage',
    },
    header: {
        idLabel: 'expense.header.idLabel',
        workerLabel: 'expense.header.workerLabel',
        currentApproversLabel: 'expense.header.currentApproversLabel',
        clientLabel: 'expense.header.clientLabel',
        workOrderLabel: 'expense.header.workOrderLabel',
        workOrderDescriptionLabel: 'expense.header.workOrderDescriptionLabel',
        noOfExpensesLabel: 'expense.header.noOfExpensesLabel',
        statusLabel: 'expense.header.statusLabel',
        lowPoMessage: 'expense.header.lowPoMessage',
        totalLabel: 'expense.header.totalLabel',
    },
    detail: {
        detailTab: 'expense.detail.detailTab',
        notesAndAttachmentsTab: 'expense.detail.notesAndAttachmentsTab',
        historyTab: 'expense.detail.historyTab',
        expenseClaimTitle: 'expense.detail.expenseClaimTitle',
        titleLabel: 'expense.detail.titleLabel',
        currencyLabel: 'expense.detail.currencyLabel',
        descriptionLabel: 'expense.detail.descriptionLabel',
        workflowhistoryTitle: 'expense.detail.workflowhistoryTitle',
        discardConfirmationMessage: 'expense.detail.discardConfirmationMessage',
        changeHistoryTitle: 'expense.detail.changeHistoryTitle',
        phoneExpenseOverage: 'expense.detail.phoneExpenseOverage'
    },
    notesAndAttachments: {
        documentHeader: 'expense.notes.documentHeader',
        expenseClaimHeader: 'expense.notes.expenseClaimHeader',
        expenseItemHeader: 'expense.notes.expenseItemHeader',
        documentDescription: 'expense.notes.documentDescription',
        expenseClaimDescription1: 'expense.notes.expenseClaimDescription1',
        expenseClaimDescription2: 'expense.notes.expenseClaimDescription2',
        expenseItemDescription: 'expense.notes.expenseItemDescription',
        placeHolderDescription: 'expense.notes.placeHolderDescription',
        uploadTitle: 'expense.notes.uploadTitle',
        confirmDeleteFile: 'expense.notes.confirmDeleteFile',
    },
    itemAdd: {
        header: 'expense.itemAdd.header',
        description: 'expense.itemAdd.description',
        dateIncurred: 'expense.itemAdd.dateIncurred',
        merchant: 'expense.itemAdd.merchant',
        country: 'expense.itemAdd.country',
        provinceOrState: 'expense.itemAdd.provinceOrState',
        subtotal: 'expense.itemAdd.subtotal',
        tip: 'expense.itemAdd.tip',
        total: 'expense.itemAdd.total',
        note: 'expense.itemAdd.note',
        placeHolderMerchant: 'expense.itemAdd.placeHolderMerchant',
        placeHolderCountry: 'expense.itemAdd.placeHolderCountry',
        placeHolderProvinceOrState: 'expense.itemAdd.placeHolderProvinceOrState',
        placeHolderNotes: 'expense.itemAdd.placeHolderNotes',
        uploadTitle: 'expense.itemAdd.uploadTitle',
        deleteConfirmation: 'expense.itemAdd.deleteConfirmation',
        successDelete: 'expense.itemAdd.successDelete',
        errorDelete: 'expense.itemAdd.errorDelete',
        saveBtn: 'expense.itemAdd.saveBtn',
        cancelBtn: 'expense.itemAdd.cancelBtn',
        removeBtn: 'expense.itemAdd.removeBtn',
        itemSaving: 'expense.itemAdd.itemSaving',
    }
};
